import React, {useEffect, useState} from 'react';
import { createRoot } from 'react-dom/client';
import {ArrowDown, ArrowRight, AudioLines, BellRing, BrainCircuit, Camera, Check, ChevronRight, CircleAlert, DoorOpen, Eye, Footprints, GitBranch, Info, MapPin, Menu, Mic, MoveRight, Navigation, PersonStanding, ShieldCheck, SlidersHorizontal, Sparkles, Speaker, Volume2, X, Zap} from 'lucide-react';
import './styles.css';

const Icon = ({name}) => { const icons={stairs:Footprints,chair:PersonStanding,wall:SlidersHorizontal,door:DoorOpen,person:PersonStanding,vehicle:Navigation}; const C=icons[name]||Info; return <C/> };
const flow=[['01','Camera',Camera],['02','Object Detection',Eye],['03','Context Analysis',BrainCircuit],['04','Risk Priority',CircleAlert],['05','Alert Filter',SlidersHorizontal],['06','Audio Guidance',Volume2]];
const objects=[
  {id:'stairs',name:'Staircase',pos:'Ahead · lower path',rel:'Critical for navigation',risk:'High',audio:'Stairs ahead. Step down.',x:'62%',y:'70%'},
  {id:'chair',name:'Chair',pos:'Left · 1.2 m',rel:'Temporary obstacle',risk:'Medium',audio:'Obstacle ahead, slightly left.',x:'25%',y:'58%'},
  {id:'door',name:'Doorway',pos:'Ahead · 3.5 m',rel:'Useful route opening',risk:'Low',audio:'Doorway ahead.',x:'74%',y:'31%'},
  {id:'person',name:'Person',pos:'Right · moving',rel:'Dynamic path obstruction',risk:'Medium',audio:'Person passing on your right.',x:'45%',y:'43%'},
  {id:'wall',name:'Wall',pos:'Right boundary',rel:'Stable reference',risk:'Low',audio:'Wall along your right.',x:'90%',y:'52%'}
];

function App(){
 const [selected,setSelected]=useState(objects[0]); const [menu,setMenu]=useState(false); const [playing,setPlaying]=useState(false);
 useEffect(()=>{const onScroll=()=>document.querySelectorAll('.reveal').forEach(el=>{if(el.getBoundingClientRect().top<window.innerHeight*.88)el.classList.add('visible')});onScroll();window.addEventListener('scroll',onScroll);return()=>window.removeEventListener('scroll',onScroll)},[]);
 const say=(txt)=>{
   setPlaying(true);
   if ('speechSynthesis' in window) {
     window.speechSynthesis.cancel();
     const message=new SpeechSynthesisUtterance(txt);
     message.rate=.9;
     message.pitch=1;
     message.onend=()=>setPlaying(false);
     message.onerror=()=>setPlaying(false);
     window.speechSynthesis.speak(message);
   } else window.setTimeout(()=>setPlaying(false),1150);
 };
 return <main>
  <div className="noise"/><div className="aurora a1"/><div className="aurora a2"/>
  <nav><a className="brand" href="#top"><span className="brandmark"><Eye/></span><span>SMARTSIGHT <i>AI</i></span></a><div className={'navlinks '+(menu?'open':'')}><a href="#idea">The idea</a><a href="#concept">Concept demo</a><a href="#technology">Technology</a><a href="#team">Team</a></div><button className="menu" onClick={()=>setMenu(!menu)}>{menu?<X/>:<Menu/>}</button><a className="navbadge" href="#concept">AVISHKAR <ArrowRight/></a></nav>
  <section className="hero" id="top"><div className="hero-copy reveal"><div className="eyebrow"><Sparkles/> AVISHKAR PROJECT PRESENTATION</div><h1>See the path.<br/><em>Feel the freedom.</em></h1><p className="subtitle">Context-Aware Obstacle Detection for Visually Impaired Users</p><p className="tagline">Detect. <b>Understand.</b> Prioritize. Guide.</p><div className="hero-ctas"><a href="#idea" className="button primary">Explore the idea <ArrowDown/></a><a href="#concept" className="button ghost"><PlayIcon/> Concept demo</a></div><div className="hero-foot"><span><ShieldCheck/> Assistive-tech concept</span><span><Info/> Not a live AI system</span></div></div><HeroVisual/></section>
  <section className="section problem" id="problem"><div className="section-head reveal"><div><span className="overline">01 / THE PROBLEM</span><h2>Objects are everywhere.<br/><em>Attention is limited.</em></h2></div><p>A list of detected things is noise. Navigation needs a system that understands which thing matters—right now.</p></div><div className="problem-grid reveal"><div className="vision-scene"><div className="scene-label"><Camera/> A typical visual field</div>{['stairs','chair','wall','door','person','vehicle'].map((x,i)=><div key={x} className={'object-chip chip-'+i}><Icon name={x}/><span>{x}</span></div>)}<div className="camera-lines"/><div className="alert-noise"><BellRing/><div><b>6 alerts at once</b><span>Too much, too fast.</span></div></div></div><div className="problem-copy"><div className="danger-icon"><CircleAlert/></div><h3>Detection ≠ direction</h3><p>“Chair. Wall. Person. Door.”<br/>What should the user hear first?</p><div className="mini-points"><span><X/> Unnecessary alerts</span><span><X/> No spatial priority</span><span><X/> Missing navigation context</span></div></div></div></section>
  <section className="section idea" id="idea"><div className="center-head reveal"><span className="overline">02 / OUR IDEA</span><h2>Make every alert <em>earn</em><br/>the user’s attention.</h2></div><div className="flow reveal">{flow.map(([n,label,C],i)=><React.Fragment key={label}><div className="flow-step"><span>{n}</span><div className="flow-icon"><C/></div><b>{label}</b></div>{i<flow.length-1&&<ChevronRight className="flow-arrow"/>}</React.Fragment>)}</div><div className="flow-caption reveal"><span><Zap/> Less noise</span><span><MapPin/> More spatial meaning</span><span><AudioLines/> Actionable guidance</span></div></section>
  <section className="section difference"><div className="section-head reveal"><div><span className="overline">03 / THE KEY DIFFERENCE</span><h2>From recognition<br/>to <em>relevance.</em></h2></div><p>SmartSight is designed around the decision a traveler needs to make—not the raw list a camera can see.</p></div><div className="compare reveal"><CompareCard type="traditional"/><div className="vs">VS</div><CompareCard type="smart"/></div></section>
  <section className="section concept" id="concept"><div className="concept-title reveal"><div><span className="overline">04 / CONTEXT-AWARE CONCEPT</span><h2>Tap the scene.<br/><em>Discover the priority.</em></h2></div><span className="conceptual"><Info/> CONCEPTUAL DEMONSTRATION</span></div><div className="demo reveal"><div className="environment"><div className="environment-top"><span><MapPin/> Simulated corridor environment</span><span>Tap a marker</span></div><div className="perspective"><div className="floor-grid"/><div className="wall left-wall"/><div className="wall right-wall"/><div className="door-shape"/><div className="stairs-shape"><i/><i/><i/><i/></div><div className="chair-shape"><i/><i/></div><div className="person-shape"/>{objects.map(o=><button key={o.id} className={'marker '+(selected.id===o.id?'active':'')} style={{left:o.x,top:o.y}} onClick={()=>setSelected(o)} aria-label={'Inspect '+o.name}><span/><Icon name={o.id}/></button>)}</div></div><InfoPanel o={selected} say={say} playing={playing}/></div><div className="object-selector reveal">{objects.map(o=><button onClick={()=>setSelected(o)} className={selected.id===o.id?'selected':''} key={o.id}><Icon name={o.id}/>{o.name}<span className={'risk '+o.risk.toLowerCase()}>{o.risk}</span></button>)}</div></section>
  <section className="section audio"><div className="audio-copy reveal"><span className="overline">05 / AUDIO GUIDANCE</span><h2>Clear words.<br/><em>Calm confidence.</em></h2><p>Short, spatial guidance that supports a safer next step—without overwhelming the listener.</p><div className="sound-bars">{[1,2,3,4,5,6,7,8,9,10,11,12,13,14].map(i=><i key={i} style={{height:(15+(i*17)%62)+'px'}}/> )}</div></div><div className="phone reveal"><div className="phone-notch"/><div className="phone-content"><div className="phone-status"><span>9:41</span><span>◌ ◒ ▰</span></div><div className="listening"><span className={playing?'pulse':''}><Volume2/></span><p>SMARTSIGHT AI</p><b>Audio guidance</b></div><button className="audio-message active" onClick={()=>say('Stairs ahead')}><span><AudioLines/></span><div><small>HIGH PRIORITY</small><b>“Stairs ahead.”</b></div><PlayIcon/></button><button className="audio-message" onClick={()=>say('Obstacle ahead')}><span><AudioLines/></span><div><small>MEDIUM PRIORITY</small><b>“Obstacle ahead.”</b></div><PlayIcon/></button><div className="voice-row"><Mic/><span>Voice feedback designed for clarity</span></div></div></div></section>
  <section className="section technology" id="technology"><div className="center-head reveal"><span className="overline">06 / PROPOSED TECHNOLOGY</span><h2>Thoughtfully chosen<br/>for <em>the journey ahead.</em></h2></div><div className="stack reveal">{[['Flutter','Mobile experience','◈'],['Dart','App logic','‹/›'],['Python','Vision pipeline','⌁'],['PyTorch','ML foundation','◉'],['YOLO','Lightweight detection','⌘'],['OpenCV','Visual processing','◌'],['Text-to-Speech','Audio output','♫'],['Git','Collaboration','⌥']].map(([a,b,c])=><div className="tech-card" key={a}><span>{c}</span><b>{a}</b><small>{b}</small></div>)}</div><p className="tech-note reveal"><Info/> Proposed architecture for future implementation — not active on this poster.</p></section>
  <section className="section roadmap"><div className="section-head reveal"><div><span className="overline">07 / SCOPE & FUTURE</span><h2>One helpful step.<br/><em>Then many more.</em></h2></div></div><div className="roadmap-grid reveal">{[['01','Indoor','Corridors, doors, stairs & fixed obstacles','Now'],['02','Outdoor','Crossings, vehicles & dynamic scenes','Next'],['03','Future','Personalized guidance & wearable integration','Beyond']].map(([n,t,d,k])=><article key={t}><span>{n}</span><div className="road-icon">{t==='Indoor'?<DoorOpen/>:t==='Outdoor'?<Navigation/>:<Sparkles/>}</div><h3>{t}</h3><p>{d}</p><small>{k} <ArrowRight/></small></article>)}</div></section>
  <section className="section limits"><div className="limits-banner reveal"><div><span className="overline">08 / DESIGN HONESTLY</span><h2>Ideas improve when<br/><em>limitations are visible.</em></h2></div><div className="limits-list">{['Lighting conditions','Camera direction','Approximate distance estimation','Mobile hardware constraints'].map((x,i)=><span key={x}><b>0{i+1}</b>{x}</span>)}</div></div></section>
  <footer id="team"><div className="final-statement reveal"><span className="overline">SMARTSIGHT AI / AVISHKAR 2026</span><h2>Not just detecting<br/>what is there —<br/><em>understanding what matters.</em></h2><div className="final-line"><span>Assistive intelligence, designed with empathy.</span><ArrowRight/></div></div><div className="team reveal"><div><span className="overline">PROJECT TEAM</span><h3>Built for Avishkar</h3></div><div className="avatars">{['Aditya Kokane','Om Jagtap','Shreya Bhujbal','Pranjal Gade'].map((x,i)=><div className="member" key={x}><span>{x[0]}</span><b>{x}</b></div>)}</div></div><div className="footer-bottom"><span>© 2026 SmartSight AI</span><span>CONCEPTUAL INTERACTIVE POSTER</span><a href="#top">Back to top ↑</a></div></footer>
 </main>
}
function HeroVisual(){return <div className="hero-art reveal"><div className="orbit o1"/><div className="orbit o2"/><div className="route route1"/><div className="person"><div className="head"/><div className="body"/><div className="cane"/></div><div className="hero-phone"><div className="speaker-notch"/><div className="screen"><div className="camera-chip"><Camera/> CONTEXT SCAN</div><div className="scan-square"><i className="corner c1"/><i className="corner c2"/><i className="corner c3"/><i className="corner c4"/><div className="mini-stairs"/><span className="scan-tag">STAIRS <b>HIGH RISK</b></span></div><div className="phone-guidance"><Volume2/><div><small>NAVIGATION ALERT</small><b>Stairs ahead</b></div></div></div></div><div className="floating f1"><BrainCircuit/><span>CONTEXT<br/><b>ANALYSIS</b></span></div><div className="floating f2"><Navigation/><span>PATH<br/><b>PRIORITY</b></span></div></div>}
function PlayIcon(){return <span className="play"><i/></span>}
function CompareCard({type}){const smart=type==='smart';return <article className={'compare-card '+type}><div className="compare-top"><span>{smart?<BrainCircuit/>:<Eye/>}</span><div><small>{smart?'SMARTSIGHT AI':'TRADITIONAL'}</small><h3>{smart?'Context-Aware Guidance':'Object Detection'}</h3></div></div><div className="compare-list">{(smart?['Navigation relevance','Position & approximate distance','Detection confidence','Risk-based priority','Filtered audio guidance']:['Objects identified','Raw detection list','Equal alert importance','No route context','Frequent interruptions']).map((x,i)=><div key={x}><span>{smart?<Check/>:<span className="dot"/>}</span>{x}{smart&&i===3&&<b>KEY</b>}</div>)}</div><div className="compare-bottom">{smart?'“Stairs ahead, step down.”':'“Chair. Wall. Person. Door.”'}</div></article>}
function InfoPanel({o,say,playing}){return <aside className="info-panel"><div className="panel-head"><div className="panel-icon"><Icon name={o.id}/></div><div><small>SELECTED OBJECT</small><h3>{o.name}</h3></div><span className={'risk '+o.risk.toLowerCase()}>{o.risk} risk</span></div><div className="detail"><span>Position</span><b>{o.pos}</b></div><div className="detail"><span>Relevance</span><b>{o.rel}</b></div><div className="priority-meter"><span>Navigation priority</span><div><i className={o.risk.toLowerCase()}/></div></div><button className={'sample-audio '+(playing?'playing':'')} onClick={()=>say(o.audio)}><span><Volume2/></span><div><small>EXAMPLE AUDIO WARNING</small><b>“{o.audio}”</b></div><PlayIcon/></button><p className="panel-disclaimer"><Info/> Conceptual information only — no real AI inference.</p></aside>}
createRoot(document.getElementById('root')).render(<App/>);
